---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  EncoderJobCreatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./output/package.zip
      Handler: convert.handler
      Runtime: python3.6
      AutoPublishAlias: dev
      Environment:
        Variables:
          DESTINATION_BUCKET: !ImportValue 'VideoDownloadBucket'
      Events:
        CreateEncodingJob:
          Type: SNS
          Properties:
            Topic: !ImportValue 'VideoUploadCreateObjectTopicArn'
