---
sys_path: .
stacker_bucket: '' # Disable running CF from bucket, run directly from here

common_tags: &common_tags
  app: ${app}
  env: ${env}

stacks:
  - name: deployment-bucket
    class_path: blueprints.bucket.Bucket
    enabled: true
    variables:
      BucketName: a1b1-${app}-${env}-deployment
      tags:
        <<: *common_tags
      exports:
        DeploymentBucket: '$\{BucketName}'
  - name: video-upload-bucket
    class_path: blueprints.bucket.BucketWithSns
    enabled: true
    variables:
      InternalBucketName: VideoUpload
      BucketName: a1b1-${app}-${env}-video-upload
      tags:
        <<: *common_tags
      exports:
        VideoUploadBucket: '$\{BucketName}'
  - name: video-download-bucket
    class_path: blueprints.bucket.Bucket
    enabled: true
    variables:
      BucketName: a1b1-${app}-${env}-video-download
      public: true
      tags:
        <<: *common_tags
      exports:
        VideoDownloadBucket: '$\{BucketName}'
  - name: encoder-job-creator-roles
    class_path: blueprints.encoder_job_creator.Roles
    enabled: true
    variables:
      tags:
        <<: *common_tags
      exports:
        EncoderJobCreatorFunctionLambdaRoleArn: '$\{LambdaRole.Arn}'
        EncoderJobCreatorFunctionMediaConvertRoleArn: '$\{MediaConvertRole.Arn}'
  - name: upload-link-generator-role
    class_path: blueprints.upload_link_generator.Role
    enabled: true
    variables:
      UploadBucket: '${output video-upload-bucket::VideoUploadBucket}'
      tags:
        <<: *common_tags
      exports:
        UploadLinkGeneratorFunctionLambdaRoleArn: '$\{LambdaRole.Arn}'
