---
sys_path: .
stacker_bucket: '' # Disable running CF from bucket, run directly from here

stacks:
  - name: deployment-bucket
    class_path: blueprints.bucket.Bucket
    enabled: true
    variables:
      BucketName: a1b1-${app}-${env}-deployment
      tags:
        app: ${app}
        env: ${env}
      exports:
        DeploymentBucket: '$\{BucketName}'
  - name: video-upload-bucket
    class_path: blueprints.bucket.Bucket
    enabled: true
    variables:
      BucketName: a1b1-${app}-${env}-video-upload
      tags:
        app: ${app}
        env: ${env}
      exports:
        VideoUploadBucket: '$\{BucketName}'
  - name: video-download-bucket
    class_path: blueprints.bucket.Bucket
    enabled: true
    variables:
      BucketName: a1b1-${app}-${env}-video-download
      tags:
        app: ${app}
        env: ${env}
      exports:
        VideoDownloadBucket: '$\{BucketName}'
